"""
Document model for generated exercise materials.
"""

from datetime import datetime
from enum import Enum as PyEnum
from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, Enum
from sqlalchemy.orm import relationship

from app.database import Base


class DocumentType(str, PyEnum):
    """Types of documents that can be generated by agents."""
    SCENARIO_BRIEF = "scenario_brief"           # Main scenario overview document
    FACILITATOR_GUIDE = "facilitator_guide"     # Guide for the exercise facilitator
    PARTICIPANT_HANDBOOK = "participant_handbook"  # Materials for participants
    INJECT_CARDS = "inject_cards"               # Cards for unexpected events/twists
    ASSESSMENT_RUBRIC = "assessment_rubric"     # Rubric for evaluating exercise outcomes
    AFTER_ACTION_TEMPLATE = "after_action_template"  # Post-exercise review template


class DocumentStatus(str, PyEnum):
    """Status of document generation."""
    PENDING = "pending"
    GENERATING = "generating"
    COMPLETED = "completed"
    FAILED = "failed"


class Document(Base):
    """Generated document for a tabletop exercise."""

    __tablename__ = "documents"

    id = Column(Integer, primary_key=True, index=True)
    tabletop_id = Column(Integer, ForeignKey("tabletops.id"), nullable=False)
    document_type = Column(Enum(DocumentType), nullable=False)
    status = Column(Enum(DocumentStatus), default=DocumentStatus.PENDING)

    # Document content sections
    title = Column(String(255), nullable=True)
    description = Column(Text, nullable=True)      # Description of the document
    content = Column(Text, nullable=True)          # Main content section
    learning_goals = Column(Text, nullable=True)   # Learning goals section

    # Generated PDF file path
    pdf_file_path = Column(String(500), nullable=True)

    # Generation metadata
    agent_name = Column(String(100), nullable=True)  # Which agent generated this
    generation_prompt = Column(Text, nullable=True)
    error_message = Column(Text, nullable=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    generated_at = Column(DateTime, nullable=True)

    # Relationships
    tabletop = relationship("Tabletop", back_populates="documents")

    def __repr__(self):
        return f"<Document(id={self.id}, type='{self.document_type}', tabletop_id={self.tabletop_id})>"


# Document type descriptions for agents
DOCUMENT_TYPE_INFO = {
    DocumentType.SCENARIO_BRIEF: {
        "name": "Scenario Brief",
        "description": "The main scenario overview document that sets the stage for the tabletop exercise.",
        "agent_role": "You are a scenario designer specializing in creating compelling exercise narratives.",
    },
    DocumentType.FACILITATOR_GUIDE: {
        "name": "Facilitator Guide",
        "description": "A comprehensive guide for the exercise facilitator with timing, prompts, and guidance.",
        "agent_role": "You are an experienced exercise facilitator helping others run effective tabletop exercises.",
    },
    DocumentType.PARTICIPANT_HANDBOOK: {
        "name": "Participant Handbook",
        "description": "Materials and background information for exercise participants.",
        "agent_role": "You are a training materials developer creating engaging participant resources.",
    },
    DocumentType.INJECT_CARDS: {
        "name": "Inject Cards",
        "description": "Cards containing unexpected events and information to be introduced during the exercise.",
        "agent_role": "You are a creative scenario writer specializing in plot twists and unexpected developments.",
    },
    DocumentType.ASSESSMENT_RUBRIC: {
        "name": "Assessment Rubric",
        "description": "Evaluation criteria and rubric for assessing exercise outcomes and participant performance.",
        "agent_role": "You are an assessment specialist designing fair and comprehensive evaluation criteria.",
    },
    DocumentType.AFTER_ACTION_TEMPLATE: {
        "name": "After Action Review Template",
        "description": "A template for conducting post-exercise reviews and capturing lessons learned.",
        "agent_role": "You are an organizational learning expert designing effective debrief processes.",
    },
}
